import React from 'react';
import TopNavbar from '../../molecules/TopNavbar/TopNavbar';
import SideNavbar from '../../molecules/SideNavbar/SideNavbar';
import './HomePage.css';

const HomePage = () => {

    return (
        <div className="base">
            <TopNavbar />
            <SideNavbar />
            <div className="container">
                <div className="content-wrapper">
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor,Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatem assumenda reprehenderit quo veritatis temporibus in, voluptates et quidem, facere atque asperiores excepturi totam ducimus impedit enim nam unde. Doloribus, maxime. sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro iure incidunt ex fugit libero assumenda officia qui doloremque. Esse corporis excepturi ea mollitia quibusdam? Nemo ut corrupti commodi pariatur expedita.</div>
                </div>
            </div>
        </div>
    )
}
export default HomePage;